namespace YKMaze.Models
{
    public enum MapStatus
    {
        /// <summary>
        /// 何もなし
        /// </summary>
        None,

        Stop_None_Left_None_Right_None,
        Stop_None_Left_None_Right_Pre0,
        Stop_None_Left_None_Right_Pre1,
        Stop_None_Left_None_Right_Pre2,
        Stop_None_Left_None_Right_Pre0_Pre2,
        Stop_None_Left_Pre0_Right_None,
        Stop_None_Left_Pre0_Right_Pre0,
        Stop_None_Left_Pre0_Right_Pre1,
        Stop_None_Left_Pre0_Right_Pre2,
        Stop_None_Left_Pre0_Right_Pre0_Pre2,
        Stop_None_Left_Pre1_Right_None,
        Stop_None_Left_Pre1_Right_Pre0,
        Stop_None_Left_Pre1_Right_Pre1,
        Stop_None_Left_Pre1_Right_Pre2,
        Stop_None_Left_Pre1_Right_Pre0_Pre2,
        Stop_None_Left_Pre2_Right_None,
        Stop_None_Left_Pre2_Right_Pre0,
        Stop_None_Left_Pre2_Right_Pre1,
        Stop_None_Left_Pre2_Right_Pre2,
        Stop_None_Left_Pre2_Right_Pre0_Pre2,
        Stop_None_Left_Pre0_Pre2_Right_None,
        Stop_None_Left_Pre0_Pre2_Right_Pre0,
        Stop_None_Left_Pre0_Pre2_Right_Pre1,
        Stop_None_Left_Pre0_Pre2_Right_Pre2,
        Stop_None_Left_Pre0_Pre2_Right_Pre0_Pre2,

        Stop_Pre0_Left_None_Right_None,
        Stop_Pre0_Left_None_Right_Pre0,
        Stop_Pre0_Left_Pre0_Right_None,
        Stop_Pre0_Left_Pre0_Right_Pre0,

        Stop_Pre1_Left_None_Right_None,
        Stop_Pre1_Left_None_Right_Pre0,
        Stop_Pre1_Left_None_Right_Pre1,
        Stop_Pre1_Left_Pre0_Right_None,
        Stop_Pre1_Left_Pre0_Right_Pre0,
        Stop_Pre1_Left_Pre0_Right_Pre1,
        Stop_Pre1_Left_Pre1_Right_None,
        Stop_Pre1_Left_Pre1_Right_Pre0,
        Stop_Pre1_Left_Pre1_Right_Pre1,

        Stop_Pre2_Left_None_Right_None,
        Stop_Pre2_Left_None_Right_Pre0,
        Stop_Pre2_Left_None_Right_Pre1,
        Stop_Pre2_Left_None_Right_Pre2,
        Stop_Pre2_Left_None_Right_Pre0_Pre2,
        Stop_Pre2_Left_Pre0_Right_None,
        Stop_Pre2_Left_Pre0_Right_Pre0,
        Stop_Pre2_Left_Pre0_Right_Pre1,
        Stop_Pre2_Left_Pre0_Right_Pre2,
        Stop_Pre2_Left_Pre0_Right_Pre0_Pre2,
        Stop_Pre2_Left_Pre1_Right_None,
        Stop_Pre2_Left_Pre1_Right_Pre0,
        Stop_Pre2_Left_Pre1_Right_Pre1,
        Stop_Pre2_Left_Pre1_Right_Pre2,
        Stop_Pre2_Left_Pre1_Right_Pre0_Pre2,
        Stop_Pre2_Left_Pre2_Right_None,
        Stop_Pre2_Left_Pre2_Right_Pre0,
        Stop_Pre2_Left_Pre2_Right_Pre1,
        Stop_Pre2_Left_Pre2_Right_Pre2,
        Stop_Pre2_Left_Pre2_Right_Pre0_Pre2,
        Stop_Pre2_Left_Pre0_Pre2_Right_None,
        Stop_Pre2_Left_Pre0_Pre2_Right_Pre0,
        Stop_Pre2_Left_Pre0_Pre2_Right_Pre1,
        Stop_Pre2_Left_Pre0_Pre2_Right_Pre2,
        Stop_Pre2_Left_Pre0_Pre2_Right_Pre0_Pre2,
    }
}
